import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'auth/welcome_screen.dart'; // Ensure this path is correct
import 'firebase_options.dart';   // Generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'HerSafe',
      theme: ThemeData(
        primaryColor: const Color(0xFF92487A),
        colorScheme: ColorScheme.fromSwatch().copyWith(
          secondary: const Color(0xFFE49BA6),
        ),
        scaffoldBackgroundColor: Colors.white,
        fontFamily: 'Roboto',
      ),
      home: const WelcomeScreen(),
    );
  }
}
